import Head from 'next/head'
import cheerio from 'cheerio'
import React,{useEffect,useState} from 'react'
import Remitly from '@/components/remitly';

const fetch = require('node-fetch');

export default function Home(props) 
{
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Remitly props={props}/>
    </>
  )
}

export async function getStaticProps ()
{
  const response = await fetch('https://www.remitly.com/us/en/india/pricing', {
    cache: 'no-cache',
    mode: 'no-cors',
    headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
    }});

	const body = await response.text();

  const $ = cheerio.load(body);
  const titleList = [];

  $('.fheif50').each((i, rate) => {
    const titleNode = $(rate);
    const titleText = titleNode.text();
    
    titleList.push(titleText);
  });

  const lastScraped = new Date().toISOString()

  return {
    props: {titleList, lastScraped},
    revalidate: 10,
  } 
};